### ISSUE TITLE
Unload and Reload Assembly are broken

### ISSUE THREAD

**Issue by spouliot** [icsharpcode/ilspy-vscode#146]
VS Code version: 1.76.0

Operation System and version: macOS 13.2.1

(MacOs or Linux) Mono version: n/a

## Steps to reproduce

* Load an assembly
* Right click and select `Reload Assembly`

or

* Right click and select `Unload Assembly`

## Expected behavior

Assembly is reloaded (or unloaded).

## Actual behavior

An error (notification) is shown.

The code path has changed (since implementation of Reload) and now goes thru `SearchBackend` and `ILSpyX` which verify the running thread.

## ilspy-vscode extension logs

```
[Error - 8:31:02 PM] OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker: Failed to handle request ilspy/removeAssembly 44 - System.InvalidOperationException: This method must always be called on the thread that owns the assembly list: 1 
   at ICSharpCode.ILSpyX.AssemblyList.VerifyAccess() in /_/ICSharpCode.ILSpyX/AssemblyList.cs:line 430
   at ICSharpCode.ILSpyX.AssemblyList.Unload(LoadedAssembly assembly) in /_/ICSharpCode.ILSpyX/AssemblyList.cs:line 390
   at ILSpy.Backend.Decompiler.SearchBackend.RemoveAssembly(String path) in /Users/poupou/git/external/ilspy-vscode/backend/src/ILSpy.Backend/Decompiler/SearchBackend.cs:line 55
   at ILSpy.Backend.Handlers.RemoveAssemblyHandler.Handle(RemoveAssemblyRequest request, CancellationToken cancellationToken) in /Users/poupou/git/external/ilspy-vscode/backend/src/ILSpy.Backend/Handlers/RemoveAssemblyHandler.cs:line 28
   at OmniSharp.Extensions.JsonRpc.JsonRpcServerServiceCollectionExtensions.RequestHandlerDecorator`2.Handle(T request, CancellationToken cancellationToken)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext() | Method='ilspy/removeAssembly' RequestId='44'
```

**Comment by spouliot** [comment]
Adding/removing assemblies from the list in multiple threads can be problematic. One way (what ILSpyX does) to solve this is to validated operations are done on that same thread.

Just like it makes sense that the communication between the frontend/backend is multi-threaded... which means the creation of the `AssemblyList` should be tracking the thread (where it was created) and dispatch further calls to that thread.

Another way is to have ILSpyX deal with this - that's what [`OpenAssembly`](https://github.com/icsharpcode/ILSpy/blob/52bab53294383595f50df76d30f33a79ae27df6f/ICSharpCode.ILSpyX/AssemblyList.cs#L303) implementation already does.

**Comment by Rpinski** [comment]
I think we need to try some quick workaround in backend, but in my opinion this is actually a flaw in ILSpyX. The `AssemblyList` code originates from ILSpy application and assumes that owner is always the main GUI thread.

**Comment by Rpinski** [comment]
Tried a workaround encapsulating creation and modification of `AssemblyList` in a separate thread. Add/Unload/Reload now work for me without issues.
