### ISSUE TITLE
[Regression] Conflict with rust-analyzer

### ISSUE THREAD

**Issue by HalfVoxel** [icsharpcode/ilspy-vscode#76]
VS Code version: 1.57.1

Operating System and version: ubuntu 20.04

Mono version: 6.12.0.122 (I think)

## Steps to reproduce

Have both ilspy and rust-analyzer installed at the same time.

## Expected  behavior

Rust-analyzer will work properly.
Note that no actual usage of ilspy is required.

## Actual behavior

Rust-analyzer gets stuck.

## ilspy-vscode extension logs

Cannot include because ilspy doesn't show up there. It's a pure rust project, so maybe it doesn't even get enabled. Though I do see the 'ILSpy Decompiled Members' tab (but it's empty).

![image](https://user-images.githubusercontent.com/1144597/123161166-5f48d880-d46f-11eb-98eb-d33487bde5ff.png)

This seems to be a recent conflict between ilspy and rust-analyzer. I'm not sure which plugin is causing the conflict (maybe both?), but there's definitely something odd happening. See the long discussion on the rust-analyzer issue: https://github.com/rust-analyzer/rust-analyzer/issues/9384

I tried downgrading to the previous ilspy version (0.10.0) and everything works fine when using that version.

**Comment by Rpinski** [comment]
Since the entry "ILSpy Backend" doesn't show up in the list, the extension didn't finish initialization. Could you post the output from ".NET Runtime" here if there is any?

**Comment by HalfVoxel** [comment]
Hi

I get
```
Downloading the .NET Runtime.
 Error!
ENOENT: no such file or directory, scandir '/home/arong/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/5.0.7/sdk'

Downloading .NET version(s) 5.0.7 ... Done!
.NET 5.0.7 executable path: /home/arong/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/5.0.7/dotnet
```

**Comment by Rpinski** [comment]
Thanks!
".NET Runtime" is new since update to 0.11 and comes from [.NET Install Tool extension](https://github.com/dotnet/vscode-dotnet-runtime), which we use to ensure the runtime is available during startup. This runtime check or the actual start of our language server seem to be the most probable reasons for the issue. I'll investigate further.

**Comment by Rpinski** [comment]
@HalfVoxel Would you mind trying the latest build of the extension:

https://github.com/icsharpcode/ilspy-vscode/suites/3089827243/artifacts/70567939

It doesn't fix anything, but it logs all steps of the startup process. This would help me a lot to analyze if one of the steps hangs or maybe blocks the extension host etc.

The artifact ZIP contains a .vsix package, which can be installed into VS Code with _Extensions_ -> ... -> _Install from VSIX..._
After installation you will see a new output category "ILSpy Extension"

![ILSpy Extension output](https://user-images.githubusercontent.com/1767539/123524228-112f1180-d6c9-11eb-85bb-caa8baf11f99.png)

Could you post the output seen there after VS Code has finished starting? And additionally, could you tell if there is anything suspicious shown in "Log (Extension Host)" output, related to ilspy-vscode or rust-analyzer?

Many thanks in advance!

**Comment by HalfVoxel** [comment]
Hi

The only output I get is
```
[11:29:47.306] Checking for .NET runtime 5.0
```

.Net runtime output is unchanged:
```
Downloading the .NET Runtime.
 Error!
ENOENT: no such file or directory, scandir '/home/arong/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/5.0.7/sdk'

Downloading .NET version(s) 5.0.7 ... Done!
.NET 5.0.7 executable path: /home/arong/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/5.0.7/dotnet
```

Log (shared):
```
[2021-06-30 11:28:23.434] [sharedprocess] [info] Deleted from disk matklad.rust-analyzer /home/arong/.vscode/extensions/matklad.rust-analyzer-0.2.646
[2021-06-30 11:28:42.637] [sharedprocess] [info] Installing the extension: icsharpcode.ilspy-vscode
[2021-06-30 11:28:43.158] [sharedprocess] [info] Extracted extension to /home/arong/.vscode/extensions/.ffa7b34f-1f21-442b-b922-c88068f1df38: icsharpcode.ilspy-vscode
[2021-06-30 11:28:43.164] [sharedprocess] [info] Renamed to /home/arong/.vscode/extensions/icsharpcode.ilspy-vscode-0.11.1
[2021-06-30 11:28:43.166] [sharedprocess] [info] Installation completed. icsharpcode.ilspy-vscode
[2021-06-30 11:28:43.258] [sharedprocess] [info] Successfully installed the extension: icsharpcode.ilspy-vscode
[2021-06-30 11:29:03.184] [sharedprocess] [info] Starting to clean up unused language packs.
```

Nothing interesting in Log (Extension Host).
There is an exception, but I don't think it's releated to ilspy:
```
[2021-06-30 11:28:23.447] [exthost] [info] extension host started
[2021-06-30 11:28:23.471] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":false,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"onAuthenticationRequest:microsoft"}
[2021-06-30 11:28:23.471] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/microsoft-authentication/dist/extension.js
[2021-06-30 11:28:23.476] [exthost] [info] ExtensionService#_doActivateExtension PolyMeilex.wgsl {"startup":false,"extensionId":{"value":"PolyMeilex.wgsl","_lower":"polymeilex.wgsl"},"activationEvent":"onLanguage:wgsl"}
[2021-06-30 11:28:23.476] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/polymeilex.wgsl-0.1.9/dist/extension.js
[2021-06-30 11:28:23.478] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-06-30 11:28:23.478] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/debug-auto-launch/dist/extension
[2021-06-30 11:28:23.480] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-06-30 11:28:23.480] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/git/dist/main
[2021-06-30 11:28:23.495] [exthost] [info] ExtensionService#_doActivateExtension slevesque.shader {"startup":true,"extensionId":{"value":"CADENAS.vscode-glsllint","_lower":"cadenas.vscode-glsllint"},"activationEvent":"*"}
[2021-06-30 11:28:23.495] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/slevesque.shader-1.1.5/out/extension
[2021-06-30 11:28:23.943] [exthost] [info] ExtensionService#_doActivateExtension lixquid.calculator {"startup":true,"extensionId":{"value":"lixquid.calculator","_lower":"lixquid.calculator"},"activationEvent":"*"}
[2021-06-30 11:28:23.943] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/lixquid.calculator-0.1.1/out/src/extension
[2021-06-30 11:28:24.063] [exthost] [info] ExtensionService#_doActivateExtension michelemelluso.code-beautifier {"startup":true,"extensionId":{"value":"michelemelluso.code-beautifier","_lower":"michelemelluso.code-beautifier"},"activationEvent":"*"}
[2021-06-30 11:28:24.063] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/michelemelluso.code-beautifier-2.3.3/out/src/extension
[2021-06-30 11:28:24.076] [exthost] [info] ExtensionService#_doActivateExtension serayuzgur.crates {"startup":true,"extensionId":{"value":"serayuzgur.crates","_lower":"serayuzgur.crates"},"activationEvent":"workspaceContains:Cargo.toml"}
[2021-06-30 11:28:24.076] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/serayuzgur.crates-0.5.9/dist/extension
[2021-06-30 11:28:24.124] [exthost] [info] ExtensionService#_doActivateExtension matklad.rust-analyzer {"startup":true,"extensionId":{"value":"matklad.rust-analyzer","_lower":"matklad.rust-analyzer"},"activationEvent":"workspaceContains:**/Cargo.toml"}
[2021-06-30 11:28:24.124] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/matklad.rust-analyzer-0.2.654/out/src/main
[2021-06-30 11:28:24.200] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-06-30 11:28:24.200] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/github/dist/extension.js
[2021-06-30 11:28:24.202] [exthost] [info] ExtensionService#_doActivateExtension CADENAS.vscode-glsllint {"startup":true,"extensionId":{"value":"CADENAS.vscode-glsllint","_lower":"cadenas.vscode-glsllint"},"activationEvent":"*"}
[2021-06-30 11:28:24.202] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/cadenas.vscode-glsllint-1.4.0/dist/extension
[2021-06-30 11:28:24.272] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2021-06-30 11:28:24.272] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js
[2021-06-30 11:28:24.367] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":false,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"onAuthenticationRequest:github"}
[2021-06-30 11:28:24.367] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/github-authentication/dist/extension.js
[2021-06-30 11:28:24.394] [exthost] [info] eager extensions activated
[2021-06-30 11:28:24.414] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":false,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"onStartupFinished"}
[2021-06-30 11:28:24.414] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/emmet/dist/node/emmetNodeMain
[2021-06-30 11:28:24.418] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":false,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"onStartupFinished"}
[2021-06-30 11:28:24.418] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/merge-conflict/dist/mergeConflictMain
[2021-06-30 11:28:24.419] [exthost] [info] ExtensionService#_doActivateExtension vscode.testing-editor-contributions {"startup":false,"extensionId":{"value":"vscode.testing-editor-contributions","_lower":"vscode.testing-editor-contributions"},"activationEvent":"onStartupFinished"}
[2021-06-30 11:28:24.419] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/testing-editor-contributions/dist/extension.js
[2021-06-30 11:28:24.420] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens {"startup":false,"extensionId":{"value":"eamodio.gitlens","_lower":"eamodio.gitlens"},"activationEvent":"onStartupFinished"}
[2021-06-30 11:28:24.420] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/eamodio.gitlens-11.5.1/dist/gitlens
[2021-06-30 11:28:48.868] [exthost] [info] extension host terminating: renderer closed the socket
[2021-06-30 11:28:48.876] [exthost] [error] TypeError: Cannot read property 'dispose' of undefined
	at t.GLSLLintingProvider.dispose (/home/arong/.vscode/extensions/cadenas.vscode-glsllint-1.4.0/dist/extension.js:2:327703)
	at Object.I [as dispose] (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:14:4668)
	at m._deactivate (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:11386)
	at /snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:9976
	at Array.map (<anonymous>)
	at m.deactivateAll (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:9964)
	at E.terminate (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:728)
	at u (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:31696)
	at Socket.<anonymous> (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:29491)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[2021-06-30 11:28:48.882] [exthost] [error] Canceled: Canceled
	at Object.s [as canceled] (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:5:1157)
	at d._remoteCall (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12889)
	at Proxy.b.<computed>.y.charCodeAt.b.<computed> (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:9409)
	at _doExecuteCommand (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:107534)
	at _.executeCommand (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:107084)
	at Object.executeCommand (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:21394)
	at Object.setContextValue (/home/arong/.vscode/extensions/matklad.rust-analyzer-0.2.654/out/src/main.js:17611:48)
	at Object.deactivate (/home/arong/.vscode/extensions/matklad.rust-analyzer-0.2.654/out/src/main.js:23238:18)
	at m._deactivate (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:11262)
	at /snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:9976
	at Array.map (<anonymous>)
	at m.deactivateAll (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:9964)
	at E.terminate (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:728)
	at u (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:31696)
	at Socket.<anonymous> (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:29491)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[2021-06-30 11:28:49.880] [exthost] [info] exiting with code 0
[2021-06-30 11:28:50.159] [exthost] [info] extension host started
[2021-06-30 11:28:50.232] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":false,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"onAuthenticationRequest:microsoft"}
[2021-06-30 11:28:50.232] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/microsoft-authentication/dist/extension.js
[2021-06-30 11:28:50.236] [exthost] [info] ExtensionService#_doActivateExtension PolyMeilex.wgsl {"startup":false,"extensionId":{"value":"PolyMeilex.wgsl","_lower":"polymeilex.wgsl"},"activationEvent":"onLanguage:wgsl"}
[2021-06-30 11:28:50.236] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/polymeilex.wgsl-0.1.9/dist/extension.js
[2021-06-30 11:28:50.237] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-06-30 11:28:50.237] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/debug-auto-launch/dist/extension
[2021-06-30 11:28:50.238] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-06-30 11:28:50.238] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/git/dist/main
[2021-06-30 11:28:50.247] [exthost] [info] ExtensionService#_doActivateExtension slevesque.shader {"startup":true,"extensionId":{"value":"CADENAS.vscode-glsllint","_lower":"cadenas.vscode-glsllint"},"activationEvent":"*"}
[2021-06-30 11:28:50.248] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/slevesque.shader-1.1.5/out/extension
[2021-06-30 11:28:50.502] [exthost] [info] ExtensionService#_doActivateExtension lixquid.calculator {"startup":true,"extensionId":{"value":"lixquid.calculator","_lower":"lixquid.calculator"},"activationEvent":"*"}
[2021-06-30 11:28:50.502] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/lixquid.calculator-0.1.1/out/src/extension
[2021-06-30 11:28:50.570] [exthost] [info] ExtensionService#_doActivateExtension michelemelluso.code-beautifier {"startup":true,"extensionId":{"value":"michelemelluso.code-beautifier","_lower":"michelemelluso.code-beautifier"},"activationEvent":"*"}
[2021-06-30 11:28:50.570] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/michelemelluso.code-beautifier-2.3.3/out/src/extension
[2021-06-30 11:28:50.578] [exthost] [info] ExtensionService#_doActivateExtension serayuzgur.crates {"startup":true,"extensionId":{"value":"serayuzgur.crates","_lower":"serayuzgur.crates"},"activationEvent":"workspaceContains:Cargo.toml"}
[2021-06-30 11:28:50.578] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/serayuzgur.crates-0.5.9/dist/extension
[2021-06-30 11:28:50.616] [exthost] [info] ExtensionService#_doActivateExtension matklad.rust-analyzer {"startup":true,"extensionId":{"value":"matklad.rust-analyzer","_lower":"matklad.rust-analyzer"},"activationEvent":"workspaceContains:**/Cargo.toml"}
[2021-06-30 11:28:50.616] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/matklad.rust-analyzer-0.2.654/out/src/main
[2021-06-30 11:28:50.663] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-06-30 11:28:50.663] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/github/dist/extension.js
[2021-06-30 11:28:50.665] [exthost] [info] ExtensionService#_doActivateExtension CADENAS.vscode-glsllint {"startup":true,"extensionId":{"value":"CADENAS.vscode-glsllint","_lower":"cadenas.vscode-glsllint"},"activationEvent":"*"}
[2021-06-30 11:28:50.665] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/cadenas.vscode-glsllint-1.4.0/dist/extension
[2021-06-30 11:28:50.744] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2021-06-30 11:28:50.744] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js
[2021-06-30 11:28:50.813] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":false,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"onAuthenticationRequest:github"}
[2021-06-30 11:28:50.813] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/github-authentication/dist/extension.js
[2021-06-30 11:28:50.909] [exthost] [info] eager extensions activated
[2021-06-30 11:28:50.918] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":false,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"onStartupFinished"}
[2021-06-30 11:28:50.918] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/emmet/dist/node/emmetNodeMain
[2021-06-30 11:28:50.921] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":false,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"onStartupFinished"}
[2021-06-30 11:28:50.921] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/merge-conflict/dist/mergeConflictMain
[2021-06-30 11:28:50.923] [exthost] [info] ExtensionService#_doActivateExtension vscode.testing-editor-contributions {"startup":false,"extensionId":{"value":"vscode.testing-editor-contributions","_lower":"vscode.testing-editor-contributions"},"activationEvent":"onStartupFinished"}
[2021-06-30 11:28:50.923] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/testing-editor-contributions/dist/extension.js
[2021-06-30 11:28:50.923] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens {"startup":false,"extensionId":{"value":"eamodio.gitlens","_lower":"eamodio.gitlens"},"activationEvent":"onStartupFinished"}
[2021-06-30 11:28:50.923] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/eamodio.gitlens-11.5.1/dist/gitlens
[2021-06-30 11:29:23.973] [exthost] [info] ExtensionService#_doActivateExtension ms-dotnettools.vscode-dotnet-runtime {"startup":false,"extensionId":{"value":"icsharpcode.ilspy-vscode","_lower":"icsharpcode.ilspy-vscode"},"activationEvent":"*"}
[2021-06-30 11:29:23.973] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.1.0/dist/extension.js
[2021-06-30 11:29:24.044] [exthost] [info] ExtensionService#_doActivateExtension icsharpcode.ilspy-vscode {"startup":false,"extensionId":{"value":"icsharpcode.ilspy-vscode","_lower":"icsharpcode.ilspy-vscode"},"activationEvent":"*"}
[2021-06-30 11:29:24.044] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/icsharpcode.ilspy-vscode-0.11.1/out/extension.js
[2021-06-30 11:29:46.522] [exthost] [info] extension host started
[2021-06-30 11:29:46.578] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":false,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"onAuthenticationRequest:microsoft"}
[2021-06-30 11:29:46.578] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/microsoft-authentication/dist/extension.js
[2021-06-30 11:29:46.583] [exthost] [info] ExtensionService#_doActivateExtension PolyMeilex.wgsl {"startup":false,"extensionId":{"value":"PolyMeilex.wgsl","_lower":"polymeilex.wgsl"},"activationEvent":"onLanguage:wgsl"}
[2021-06-30 11:29:46.583] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/polymeilex.wgsl-0.1.9/dist/extension.js
[2021-06-30 11:29:46.584] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-06-30 11:29:46.584] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/debug-auto-launch/dist/extension
[2021-06-30 11:29:46.585] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-06-30 11:29:46.585] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/git/dist/main
[2021-06-30 11:29:46.593] [exthost] [info] ExtensionService#_doActivateExtension slevesque.shader {"startup":true,"extensionId":{"value":"CADENAS.vscode-glsllint","_lower":"cadenas.vscode-glsllint"},"activationEvent":"*"}
[2021-06-30 11:29:46.594] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/slevesque.shader-1.1.5/out/extension
[2021-06-30 11:29:46.841] [exthost] [info] ExtensionService#_doActivateExtension ms-dotnettools.vscode-dotnet-runtime {"startup":true,"extensionId":{"value":"icsharpcode.ilspy-vscode","_lower":"icsharpcode.ilspy-vscode"},"activationEvent":"*"}
[2021-06-30 11:29:46.841] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.1.0/dist/extension.js
[2021-06-30 11:29:46.896] [exthost] [info] ExtensionService#_doActivateExtension lixquid.calculator {"startup":true,"extensionId":{"value":"lixquid.calculator","_lower":"lixquid.calculator"},"activationEvent":"*"}
[2021-06-30 11:29:46.896] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/lixquid.calculator-0.1.1/out/src/extension
[2021-06-30 11:29:46.956] [exthost] [info] ExtensionService#_doActivateExtension michelemelluso.code-beautifier {"startup":true,"extensionId":{"value":"michelemelluso.code-beautifier","_lower":"michelemelluso.code-beautifier"},"activationEvent":"*"}
[2021-06-30 11:29:46.956] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/michelemelluso.code-beautifier-2.3.3/out/src/extension
[2021-06-30 11:29:46.963] [exthost] [info] ExtensionService#_doActivateExtension serayuzgur.crates {"startup":true,"extensionId":{"value":"serayuzgur.crates","_lower":"serayuzgur.crates"},"activationEvent":"workspaceContains:Cargo.toml"}
[2021-06-30 11:29:46.963] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/serayuzgur.crates-0.5.9/dist/extension
[2021-06-30 11:29:47.017] [exthost] [info] ExtensionService#_doActivateExtension matklad.rust-analyzer {"startup":true,"extensionId":{"value":"matklad.rust-analyzer","_lower":"matklad.rust-analyzer"},"activationEvent":"workspaceContains:**/Cargo.toml"}
[2021-06-30 11:29:47.017] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/matklad.rust-analyzer-0.2.654/out/src/main
[2021-06-30 11:29:47.100] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-06-30 11:29:47.100] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/github/dist/extension.js
[2021-06-30 11:29:47.102] [exthost] [info] ExtensionService#_doActivateExtension CADENAS.vscode-glsllint {"startup":true,"extensionId":{"value":"CADENAS.vscode-glsllint","_lower":"cadenas.vscode-glsllint"},"activationEvent":"*"}
[2021-06-30 11:29:47.102] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/cadenas.vscode-glsllint-1.4.0/dist/extension
[2021-06-30 11:29:47.137] [exthost] [info] ExtensionService#_doActivateExtension icsharpcode.ilspy-vscode {"startup":true,"extensionId":{"value":"icsharpcode.ilspy-vscode","_lower":"icsharpcode.ilspy-vscode"},"activationEvent":"*"}
[2021-06-30 11:29:47.137] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/arong/.vscode/extensions/icsharpcode.ilspy-vscode-0.11.1/out/extension.js
[2021-06-30 11:29:47.249] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2021-06-30 11:29:47.249] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js
[2021-06-30 11:29:47.337] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":false,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"onAuthenticationRequest:github"}
[2021-06-30 11:29:47.337] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/67/usr/share/code/resources/app/extensions/github-authentication/dist/extension.js
```

**Comment by Rpinski** [comment]
@HalfVoxel Thank you very much for your reply! It looks like initialization of the extension is blocked at some point when checking .NET runtime. We are investigating with .NET Install Tool people and they asked for their logs as well. Sorry for bothering you, but maybe you could help once again?

After VS Code has started and extensions have been loaded, could you select `.NET Install Tool: Report an issue with the .NET Install Tool for Extension Authors` from command palette (CTRL+Shift+P) and post the contents of the log file which is mentioned in the opened GitHub issue template? There is no need to save that issue, just post the log here, if it's not empty. 

Thank you very much!

**Comment by Rpinski** [comment]
Finally found the issue related to check of .NET runtime's dependencies on Linux, which caused the startup process to hang. Sorry for the inconvenience, will be fixed ASAP with next extension update.
